name: mens_lifes
description: Aplicativo de saÃºde
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/menslife_icon.png"
  adaptive_icon_background: "#1565C0"
  adaptive_icon_foreground: "assets/images/menslife_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/menslife_icon.png
